Update update-submodules.yml
Perhaps a fix to update RYD?

diff --git a/.github/workflows/update-submodules.yml b/.github/workflows/update-submodules.yml
--- a/.github/workflows/update-submodules.yml
+++ b/.github/workflows/update-submodules.yml
@@ -1,46 +1,32 @@
----
-name: Update submodules!
+name: Update Submodules
 
-#############################
-# Start the job on all push #
-#############################
 on:
-  push:
-      branches: [main]
-  pull_request:
-    branches: [main]
+  workflow_dispatch:
 
-
-permissions: read-all
-###############
-# Set the Job #
-###############
 jobs:
-  build:
-    name: Update submodules
+  update-submodules:
     runs-on: ubuntu-latest
-    env:
-      PARENT_REPOSITORY: 'kinggamma123/uYouPlus'
-      CHECKOUT_BRANCH: 'main'
-      PR_AGAINST_BRANCH: 'main'
-      OWNER: 'kinggamma123'
 
     steps:
-      ##########################
-      # Checkout the code base #
-      ##########################
-      - name: Checkout Code
+      - name: Checkout code
         uses: actions/checkout@v4.1.0
 
-      ####################################
-      # Run the action against code base #
-      ####################################
-      - name: run action
-        id: run_action
-        uses: kinggamma123/github-action-create-pr-parent-submodule@main
-        with:
-          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
-          parent_repository: ${{ env.PARENT_REPOSITORY }}
-          checkout_branch: ${{ env.CHECKOUT_BRANCH }}
-          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
-          owner: ${{ env.OWNER }}
+      - name: Set up Git
+        run: |
+           git config --global user.email "actions@github.com"
+           git config --global user.name "GitHub Actions"
+
+      - name: Update submodules
+        run: |
+          git submodule update --init --recursive
+          git commit -am "update submodules"
+          git push
+        continue-on-error: true
+
+      - name: Check exit code
+        run: |
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Submodule update failed with exit code $exit_code"
+            exit 1
+          fi
